# This file should define what runs in the container, how to build it, and what commands to execute
# command overrides the default CMD in the Dockerfile, so it runs pytest with the specified options when the container starts
# Build the image -> create containers -> run the command in the container -> output report to mounted volume

services:
  tests:
    build: .              # Build image from ./Dockerfile
    image: mdb-api-tests  # Tag the image for easier reference and aligned with GH Actions workflow
    container_name: tmdb-api-tests
    env_file:
      - .env        # Load all env vars from your .env file
    volumes:
      - ./report:/app/report  # Mount report dir so HTML persists
    command: >
      pytest tests/
      --html=report/tmdb_full_report.html
      --self-contained-html
      -v -s
