name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Grant GITHUB_TOKEN the permissions required for Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Poetry
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies via Poetry
      run: poetry install --no-interaction --no-root

    - name: Create report directory
      # Ensure the report directory exists
      run: mkdir -p report

    - name: Create .env file
      run: |
        echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env
        echo "TMDB_SESSION_ID=${{ secrets.TMDB_SESSION_ID }}" >> .env
        echo "TMDB_AUTH_TOKEN=${{ secrets.TMDB_AUTH_TOKEN }}" >> .env
        echo "TMDB_REQ_TOKEN=${{ secrets.TMDB_REQ_TOKEN }}" >> .env

    - name: Run Integration + Contract Tests
      run: |
        poetry run pytest tests/ \
        --html=report/tmdb_full_report.html \
        --self-contained-html -v -s
      env:
        PYTEST_ADDOPTS: "--color=yes"

    - name: Deploy & Upload/Append to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./report
        destination_dir: report      # Content goes into https://pgundlupetvenkatesh.github.io/mdb_api_layer/report/tmdb_full_report.html
        keep_files: true            # Prevents deleting docs or reports